#!/usr/bin/env python3
"""Fails if an APK carries Google code F-Droid would reject.

F-Droid's inclusion policy rejects proprietary dependencies outright rather than flagging
them, so this guards the property the fdroid flavor exists for. It is an allowlist rather
than a hunt for `firebase`: a denylist only catches the proprietary libraries someone
thought of, while anything arriving transitively later would sail through.

Not every `com.google.*` package is proprietary, and both apps legitimately ship several.
Each root below is on the classpath today and is Apache-2.0. Adding to this list is a
decision, not a formality: check the new package's licence, and if it is not free software
it must not ship rather than be allowed here.

Usage:  verify-fdroid-apk.py <apk> [<apk> ...]
"""

import collections
import re
import sys
import zipfile

# Class references appear in dex as type descriptors, `Lcom/google/common/base/Strings;`.
# Anchoring on the leading `L` keeps incidental strings (protobuf descriptor data names a
# few packages it does not ship) from being read as shipped classes.
CLASS_REF = re.compile(rb"Lcom/google/([a-zA-Z0-9_]+)")

ALLOWED_ROOTS = {
    # Guava and the annotation artifacts it drags along
    "common",
    "thirdparty",
    "errorprone",
    # protobuf runtime, plus the Google API protos that grpc-protobuf pulls in
    "protobuf",
    "api",
    "apps",
    "cloud",
    "geo",
    "logging",
    "longrunning",
    "rpc",
    "shopping",
    "type",
    # gson, auto-value annotations, accompanist (Compose helper)
    "gson",
    "auto",
    "accompanist",
    # libphonenumber, whose group id is com.googlecode.libphonenumber
    "i18n",
}

# Generated by the google-services plugin. Harmless strings on their own, but their presence
# means the plugin reached a variant it has no business in.
GOOGLE_SERVICES_RESOURCES = (b"google_app_id", b"google_api_key", b"gcm_defaultSenderId")


def check(path: str) -> list[str]:
    """Returns a list of problems, empty when the APK is clean."""
    problems = []
    with zipfile.ZipFile(path) as z:
        roots: collections.Counter[str] = collections.Counter()
        for entry in z.namelist():
            if entry.endswith(".dex"):
                for match in CLASS_REF.finditer(z.read(entry)):
                    roots[match.group(1).decode()] += 1

        for root, count in sorted(roots.items()):
            if root not in ALLOWED_ROOTS:
                problems.append(f"com.google.{root} ({count} class references)")

        try:
            arsc = z.read("resources.arsc")
        except KeyError:
            arsc = b""
        for marker in GOOGLE_SERVICES_RESOURCES:
            if marker in arsc:
                problems.append(f"{marker.decode()} resource from the google-services plugin")

    return problems


def main(argv: list[str]) -> int:
    apks = argv[1:]
    if not apks:
        print("usage: verify-fdroid-apk.py <apk> [<apk> ...]", file=sys.stderr)
        return 2

    failed = False
    for apk in apks:
        name = apk.rsplit("/", 1)[-1]
        problems = check(apk)
        if problems:
            failed = True
            for problem in problems:
                # ::error:: is picked up as an annotation when this runs in GitHub Actions.
                print(f"::error file={apk}::{name} carries {problem}")
        else:
            print(f"clean: {name}")

    if failed:
        print(
            "\nAn APK carries Google code that is not on the allowlist in this script. "
            "Either the package is free software and belongs in ALLOWED_ROOTS, or it is "
            "proprietary and must be kept out of the build.",
            file=sys.stderr,
        )
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
