#!/usr/bin/env python3
"""Fails if an APK ships Google code that must never reach an F-Droid build.

Deliberately narrow. `verify-fdroid-dependencies.py` is the gate that decides whether a Google
dependency may ship at all: it checks resolved artifact coordinates, which is the unit a licence
attaches to, and both CI jobs run it before this one. What is left for an APK scan is the two
things a coordinate check structurally cannot see:

  - Code that arrives without a coordinate of its own. A shaded or bundled artifact carries
    classes under package names unrelated to the coordinate that delivered them.
  - Anything a Gradle plugin generates rather than a dependency supplying. The google-services
    plugin injecting its keys into the fdroid variant was a real leak on this branch, and no
    dependency list would ever have shown it.

An earlier version of this script also kept an allowlist of permitted `com.google.*` package
roots. That is gone. A dex descriptor carries no package/class boundary, so it could only match
the first segment after `com.google` and had to approve roots as broad as `api`, which made it
impossible to verify by inspection and caught nothing the coordinate check does not catch
earlier and better.

Usage:  verify-fdroid-apk.py <apk> [<apk> ...]
"""

import collections
import sys
import zipfile

# Matched at any depth, so re-admitting one of these takes more than widening a list somewhere.
# Class references appear in dex as type descriptors, hence the leading `L`.
DENIED_PREFIXES = (
    b"Lcom/google/android/gms",
    b"Lcom/google/android/play",
    b"Lcom/google/firebase",
    b"Lcom/google/mlkit",
    b"Lcom/google/ar/core",
)

# Generated by the google-services plugin. Harmless strings on their own, but their presence
# means the plugin reached a variant it has no business in.
GOOGLE_SERVICES_RESOURCES = (b"google_app_id", b"google_api_key", b"gcm_defaultSenderId")


def check(path: str) -> list[str]:
    """Returns a list of problems, empty when the APK is clean."""
    problems = []
    with zipfile.ZipFile(path) as z:
        denied: collections.Counter[str] = collections.Counter()
        for entry in z.namelist():
            if not entry.endswith(".dex"):
                continue
            dex = z.read(entry)
            for prefix in DENIED_PREFIXES:
                if (count := dex.count(prefix)) > 0:
                    denied[prefix.decode().removeprefix("L").replace("/", ".")] += count

        for package, count in sorted(denied.items()):
            problems.append(f"{package} ({count} class references)")

        try:
            arsc = z.read("resources.arsc")
        except KeyError:
            arsc = b""
        for marker in GOOGLE_SERVICES_RESOURCES:
            if marker in arsc:
                problems.append(f"the {marker.decode()} resource from the google-services plugin")

    return problems


def main(argv: list[str]) -> int:
    apks = argv[1:]
    if not apks:
        print("usage: verify-fdroid-apk.py <apk> [<apk> ...]", file=sys.stderr)
        return 2

    failed = False
    for apk in apks:
        name = apk.rsplit("/", 1)[-1]
        # An unreadable path must not look like a rejection. A glob that matched nothing
        # reaches here as its own literal pattern, and exiting 1 on that would read as
        # "the APK is dirty" when the truth is "there is no APK".
        try:
            problems = check(apk)
        except (OSError, zipfile.BadZipFile) as error:
            print(f"::error file={apk}::cannot read {name}: {error}", file=sys.stderr)
            return 2
        if problems:
            failed = True
            for problem in problems:
                # ::error:: is picked up as an annotation when this runs in GitHub Actions.
                print(f"::error file={apk}::{name} carries {problem}")
        else:
            print(f"clean: {name}")

    if failed:
        print(
            "\nAn APK carries Google code that cannot ship on F-Droid. If it came from a "
            "dependency, verify-fdroid-dependencies.py should have caught it first and the "
            "mismatch is worth understanding; if not, something is generating or bundling it "
            "into the build.",
            file=sys.stderr,
        )
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
